export const bookingDetailsConstants = {
    BOOKING_DETAILS_LOCATION: "BOOKING_DETAILS_LOCATION",
    BOOKING_DETAILS_TIME: "BOOKING_DETAILS_TIME",
    BOOKING_DETAILS_SERVICES: "BOOKING_DETAILS_SERVICES",
    BOOKING_DETAILS_PARKINGLOCATION: "BOOKING_DETAILS_PARKINGLOCATION",
    BOOKING_DETAILS_AMOUNT: "BOOKING_DETAILS_AMOUNT",
}