export const userDataConstants = {
    USER_DATA_UPDATE_COMPLETE: "USER_DATA_UPDATE_COMPLETE",
    USER_DATA_UPDATE_NAME: "USER_DATA_UPDATE_NAME",
    USER_DATA_UPDATE_EMAIL: "USER_DATA_UPDATE_EMAIL",
    USER_DATA_UPDATE_PHONE_NUMBER: "USER_DATA_UPDATE_PHONE_NUMBER",
    USER_DATA_UPDATE_TOKEN: "USER_DATA_UPDATE_TOKEN",
    USER_DATA_UPDATE_HISTORY: "USER_DATA_UPDATE_HISTORY",
}

