export const userDataConstants = {
    USER_DATA_UPDATE_COMPLETE: "USER_DATA_UPDATE_COMPLETE",
    USER_DATA_UPDATE_FIRST_NAME: "USER_DATA_UPDATE_FIRST_NAME",
    USER_DATA_UPDATE_LAST_NAME: "USER_DATA_UPDATE_LAST_NAME",
    USER_DATA_UPDATE_EMAIL: "USER_DATA_UPDATE_EMAIL",
    USER_DATA_UPDATE_PHONE_NUMBER: "USER_DATA_UPDATE_PHONE_NUMBER",
}

